### PR TITLE
fix: validate ascii strings + cannot create already existing program + numprocs must be > 0 + restart processes on hot reload

### LINKED ISSUE #73: Check if a program with the same name does not yet exist when creating one
Currently when we try to create a program, if a program with the same name already exists, its configuration will be updated with the configuration with which we wanted to start a new program.

### LINKED ISSUE #74: Reject the configuration if a string field contains non-ASCII characters
Currently, such a string as `"with wtf characters \b\t\0\U0001F479"` makes the application crash because we can not create a path (for stdout) using `nul` characters.

### LINKED ISSUE #79: Restart alive process if its configuration is hot reloaded
When the configuration of a program is hot reloaded, we should create or delete processes according to the new `numprocs` value.
Currently it works correctly.
But we should also restart running processes so the configuration updates are directly taken into account.

### LINKED ISSUE #92: Numprocs must be > 0
Because it makes no sense to have 0 process

### PR DESCRIPTION
**Pull request by plcharriere**
Closes #73
Closes #74
Closes #79 
Closes #92

### CODE REVIEW

**Comment by plcharriere** [comment]
Closes #73 
Closes #74

File: cmd/taskmasterd/program.go [hunk 1]
```diff
@@ -208,6 +208,8 @@ func (program *Program) setConfig(task Tasker) error {
 
 	program.configuration = newConfig
 
+	program.restartAllProcesses(nil)
```
Comment (Devessier) [inline cmd/taskmasterd/program.go]: I am not sure we should restart all the processes independently of the properties that changed.
Some configuration changes do not require running processes to be restarted. For example, If `exitcodes` list changes, restarting processes is unnecessary. 
To me we should determine if processes have to be restarted according to properties that changed.

File: cmd/taskmasterd/yaml.go [hunk 2]
```diff
@@ -280,6 +288,12 @@ func (program *ProgramYaml) Validate(args ProgramYamlValidateArgs) (ProgramConfi
 	}
 
 	if program.Workingdir != nil {
+		if !isASCII(*program.Workingdir) {
```
Comment (Devessier) [inline cmd/taskmasterd/yaml.go]: One thing to note if we accept only ASCII paths is that any accented character will be refused.
Apparently the solely character that is not permitted in a UNIX path is the `nul` character: https://stackoverflow.com/a/537833/11780994.
As being permissive in this area of the application does not lead to crashes or bugs, we should probably just create a function `isPathValid` that checks if the path contains a `nul` character.

To me we could use the same approach for `Name` field (that we must validate because if `Stdout` or `Stderr` properties are not filled, they will be computed using `Name` property), `Cmd`, `Stdout` and `Stderr`.

File: cmd/taskmasterd/yaml.go [hunk 3]
```diff
@@ -376,6 +402,15 @@ func (program *ProgramYaml) Validate(args ProgramYamlValidateArgs) (ProgramConfi
 	return config, nil
 }
 
+func isASCII(s string) bool {
+	for i := 0; i < len(s); i++ {
```
Comment (Devessier) [inline cmd/taskmasterd/yaml.go]: Technically speaking, to loop over a string we can use a regular `range`.

**Review by Devessier — CHANGES_REQUESTED** [review]
We should talk about the way we validate strings.
Perhaps we decided too quickly to invalidate a string if it contains non-ASCII characters. But the problem we underlined was really that a `nul` character was in the program `Name`, that is in the computed `Stdout` string: https://github.com/42Taskmaster/taskmaster/issues/74#issue-820099907.

We should also discuss about processes restarting. It would probably better to only restart processes if something meaningful changed in the configuration.
And a mad corrector would not be able to reject our project according to the following sentence in the subject:
> mais il ne doit PAS supprimer les processus qui n’ont pas subit de changements avec le rechargement

**Review by Devessier — APPROVED** [review]
Great security improvements!
We can merge.
